name: CI/CD

#Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  install:
    name: ls -l
    runs-on: ubuntu-latest

    steps:
      - name: ls -l
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ec2-18-220-190-32.us-east-2.compute.amazonaws.com
          username: deployment
          password: 4!1*VjBzGk8w
          script: whoami