name: CI/CD

#Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  install:
    name: ls -l
    runs-on: ubuntu-latest

    steps:
      - name: ls -l
        uses: appleboy/ssh-action@v0.1.8
        with:
          script: ls -lh
          host: ${{secrets.HOST_DNS}}
          username: ${{secrets.USER_NAME}}
          key: ${{secrets.SSH_KEY}}